name: ktc_dart
description: A package that implemented the features of the `Collections` library of `Kotlin` (v1.5).
version: 2.0.0

repository: https://github.com/Sugyo-In/ktc_dart.git
issue_tracker: https://github.com/Sugyo-In/ktc_dart/issues

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.19.1
  meta: ^1.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.17.9
